# Generated by Django 4.2.10 on 2024-02-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='+256755565556', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
